export const searchDoctorsData = [
  {
    id: "dr-1",
    name: "Dr. Rajiv Menon",
    speciality: "Cardiologist",
    degrees: "MBBS, MD (General Medicine)",
    hospital: "Mazumdar Shaw Medical Centre",
    hospitalCount: "+1",
    city: "Bangalore",
    experience: "22 Years",
    rating: 4.9,
    reviews: 1240,
    available: "Available Today",
    availability: {
      hospital: "Today, 02:30 PM",
      video: "Today, 10:00 AM"
    },
    img: "/images/misc/doctor_avatar_male_v2.png",
    fee: "₹1,950",
  },
  {
    id: "dr-2",
    name: "Dr. Priya Sharma",
    speciality: "Neurologist",
    degrees: "MBBS, MD, DM (Neurology)",
    hospital: "NH Kolkata",
    hospitalCount: "",
    city: "Kolkata",
    experience: "15 Years",
    rating: 4.8,
    reviews: 890,
    available: "Next Available: Tomorrow",
    availability: {
      hospital: "Tomorrow, 11:00 AM",
      video: "Tomorrow, 04:00 PM"
    },
    img: "/images/misc/doctor_avatar_female_v2.png",
    fee: "₹1,200",
    isExecutive: true,
  },
  {
    id: "dr-3",
    name: "Dr. Arun Krishnan",
    speciality: "Oncologist",
    degrees: "MBBS, MS, MCh (Surgical Oncology)",
    hospital: "NH Bangalore",
    hospitalCount: "+2",
    city: "Bangalore",
    experience: "28 Years",
    rating: 4.9,
    reviews: 2100,
    available: "Available Today",
    availability: {
      hospital: "Today, 05:30 PM",
      video: "Tomorrow, 09:00 AM"
    },
    img: "/images/misc/doctor_avatar_male_v2.png",
    fee: "₹2,000",
  },
  {
    id: "dr-4",
    name: "Dr. Sunita Patel",
    speciality: "Orthopaedics",
    degrees: "MBBS, MS (Orthopaedics)",
    hospital: "NH Ahmedabad",
    hospitalCount: "",
    city: "Ahmedabad",
    experience: "18 Years",
    rating: 4.7,
    reviews: 560,
    available: "Available Today",
    availability: {
      hospital: "Tomorrow, 01:00 PM",
      video: "Today, 03:00 PM"
    },
    img: "/images/misc/doctor_avatar_female_v2.png",
    fee: "₹1,000",
  },
  {
    id: "dr-5",
    name: "Dr. Mohammed Raza",
    speciality: "Cardiologist",
    degrees: "MBBS, MD, DM (Cardiology)",
    hospital: "NH Mumbai",
    hospitalCount: "+1",
    city: "Mumbai",
    experience: "20 Years",
    rating: 4.8,
    reviews: 980,
    available: "Next Available: Day After",
    availability: {
      hospital: "Tue, 10:30 AM",
      video: "Tomorrow, 06:00 PM"
    },
    img: "/images/misc/doctor_avatar_male_v2.png",
    fee: "₹1,800",
  },
  {
    id: "dr-6",
    name: "Dr. Ananya Roy",
    speciality: "Neurologist",
    degrees: "MBBS, MD (Medicine)",
    hospital: "NH Kolkata",
    hospitalCount: "",
    city: "Kolkata",
    experience: "12 Years",
    rating: 4.6,
    reviews: 430,
    available: "Available Today",
    availability: {
      hospital: "Today, 04:30 PM",
      video: "Today, 07:00 PM"
    },
    img: "/images/misc/doctor_avatar_female_v2.png",
    fee: "₹900",
  },
  {
    id: "dr-7",
    name: "Dr. Sandeep Kumar",
    speciality: "Orthopedic Surgery",
    degrees: "MBBS, MS (Orthopedics), Fellowship in Joint Replacement",
    hospital: "NH Guwahati",
    hospitalCount: "",
    city: "Guwahati",
    experience: "16 Years",
    rating: 4.5,
    reviews: 320,
    available: "Available Tomorrow",
    availability: {
      hospital: "Tomorrow, 10:00 AM",
      video: "Tomorrow, 04:30 PM"
    },
    img: "/images/misc/doctor_avatar_male_v2.png",
    fee: "₹800",
  },
  {
    id: "dr-8",
    name: "Dr. Vikram Singh",
    speciality: "Interventional Cardiology",
    degrees: "MBBS, MD, DM (Cardiology), FACC",
    hospital: "NH Jaipur",
    hospitalCount: "+1",
    city: "Jaipur",
    experience: "25 Years",
    rating: 4.9,
    reviews: 1540,
    available: "Next Available: Monday",
    availability: {
      hospital: "Mon, 11:30 AM",
      video: "Mon, 04:00 PM"
    },
    img: "/images/misc/doctor_avatar_male_v2.png",
    fee: "₹2,500",
    isExecutive: true,
  },
  {
    id: "dr-9",
    name: "Dr. Meera Nanda",
    speciality: "Medical Oncology",
    degrees: "MBBS, MD, DM (Medical Oncology)",
    hospital: "NH Delhi",
    hospitalCount: "",
    city: "Delhi",
    experience: "19 Years",
    rating: 4.7,
    reviews: 845,
    available: "No Slots Available",
    availability: {
      hospital: "Today, 02:00 PM",
      video: "26 Jan, 11:00 AM"
    },
    img: "/images/misc/doctor_avatar_female_v2.png",
    fee: "₹1,500",
  },
  {
    id: "dr-10",
    name: "Dr. Sameer Desai",
    speciality: "Pediatric Cardiology",
    degrees: "MBBS, MD (Pediatrics), FNB (Pediatric Cardiology)",
    hospital: "NH Mumbai",
    hospitalCount: "+2",
    city: "Mumbai",
    experience: "14 Years",
    rating: 4.8,
    reviews: 670,
    available: "Available Today",
    availability: {
      hospital: "Today, 03:00 PM",
      video: "Today, 05:00 PM"
    },
    img: "/images/misc/doctor_avatar_male_v2.png",
    fee: "₹1,100",
  },
  {
    id: "dr-11",
    name: "Dr. Kavita Reddy",
    speciality: "Surgical Oncology",
    degrees: "MBBS, MS, MCh (Surgical Oncology)",
    hospital: "NH Bangalore",
    hospitalCount: "",
    city: "Bangalore",
    experience: "21 Years",
    rating: 4.9,
    reviews: 1120,
    available: "Available Tomorrow",
    availability: {
      hospital: "Tomorrow, 09:30 AM",
      video: "Tomorrow, 12:00 PM"
    },
    img: "/images/misc/doctor_avatar_female_v2.png",
    fee: "₹1,800",
  },
  {
    id: "dr-12",
    name: "Dr. Ananya Sharma",
    speciality: "Joint Replacement",
    degrees: "MBBS, MS (Orthopedics)",
    hospital: "NH Shimoga",
    hospitalCount: "",
    city: "Shimoga",
    experience: "12 Years",
    rating: 4.6,
    reviews: 450,
    available: "Available Today",
    availability: {
      hospital: "Today, 02:00 PM",
      video: "Today, 05:00 PM"
    },
    img: "/images/misc/doctor_avatar_female_v2.png",
    fee: "₹750",
  },
  {
    id: "dr-13",
    name: "Dr. Rahul Verma",
    speciality: "Neuro Surgery",
    degrees: "MBBS, MS, MCh (Neurosurgery)",
    hospital: "NH Dharwad",
    hospitalCount: "",
    city: "Dharwad",
    experience: "22 Years",
    rating: 4.8,
    reviews: 1100,
    available: "Next Available: Tomorrow",
    availability: {
      hospital: "Tomorrow, 10:30 AM",
      video: "Tomorrow, 03:00 PM"
    },
    img: "/images/misc/doctor_avatar_male_v2.png",
    fee: "₹1,800",
  },
  {
    id: "dr-14",
    name: "Dr. Siddharth Rao",
    speciality: "Interventional Cardiology",
    degrees: "MBBS, MD, DM (Cardiology)",
    hospital: "NH Ahmedabad",
    hospitalCount: "+1",
    city: "Ahmedabad",
    experience: "18 Years",
    rating: 4.7,
    reviews: 890,
    available: "Available Today",
    availability: {
      hospital: "Today, 04:00 PM",
      video: "Today, 08:00 PM"
    },
    img: "/images/misc/doctor_avatar_male_v2.png",
    fee: "₹1,200",
  },
  {
    id: "dr-15",
    name: "Dr. Sneha Patil",
    speciality: "Medical Oncology",
    degrees: "MBBS, MD (Medicine), DM (Oncology)",
    hospital: "NH Kolar",
    hospitalCount: "",
    city: "Kolar",
    experience: "15 Years",
    rating: 4.9,
    reviews: 650,
    available: "Available Tomorrow",
    availability: {
      hospital: "Tue, 09:00 AM",
      video: "Tomorrow, 01:00 PM"
    },
    img: "/images/misc/doctor_avatar_female_v2.png",
    fee: "₹1,000",
  },
  {
    id: "dr-16",
    name: "Dr. Kunal Basu",
    speciality: "Pediatric Cardiology",
    degrees: "MBBS, MD, Fellowship in Pediatric Cardiology",
    hospital: "NH Barasat",
    hospitalCount: "",
    city: "Barasat",
    experience: "11 Years",
    rating: 4.5,
    reviews: 210,
    available: "Next Available: Thursday",
    availability: {
      hospital: "Today, 11:00 AM",
      video: "26 Jan, 10:00 AM"
    },
    img: "/images/misc/doctor_avatar_male_v2.png",
    fee: "₹900",
  },
  {
    id: "dr-17",
    name: "Dr. Amitab Ghosh",
    speciality: "Surgical Oncology",
    degrees: "MBBS, MS, MCh (Surgical Oncology)",
    hospital: "NH Jamshedpur",
    hospitalCount: "+2",
    city: "Jamshedpur",
    experience: "26 Years",
    rating: 4.9,
    reviews: 1800,
    available: "Available Today",
    availability: {
      hospital: "Today, 12:30 PM",
      video: "Today, 05:30 PM"
    },
    img: "/images/misc/doctor_avatar_male_v2.png",
    fee: "₹2,200",
    isExecutive: true,
  },
  {
    id: "dr-18",
    name: "Dr. Ritu Singh",
    speciality: "Orthopedic Surgery",
    degrees: "MBBS, MS (Orthopedics)",
    hospital: "NH Gurugram",
    hospitalCount: "",
    city: "Gurugram",
    experience: "14 Years",
    rating: 4.7,
    reviews: 740,
    available: "Available Today",
    availability: {
      hospital: "Today, 09:00 AM",
      video: "Today, 11:00 AM"
    },
    img: "/images/misc/doctor_avatar_female_v2.png",
    fee: "₹1,500",
  },
  {
    id: "dr-19",
    name: "Dr. Tariq Khan",
    speciality: "Neuro Surgery",
    degrees: "MBBS, MS, MCh (Neurosurgery)",
    hospital: "NH Howrah",
    hospitalCount: "+1",
    city: "Howrah",
    experience: "20 Years",
    rating: 4.8,
    reviews: 1300,
    available: "No Slots Available",
    availability: {
      hospital: "29 Jan, 10:00 AM",
      video: "29 Jan, 04:00 PM"
    },
    img: "/images/misc/doctor_avatar_male_v2.png",
    fee: "₹1,600",
  },
  {
    id: "dr-20",
    name: "Dr. Priti Gowda",
    speciality: "Joint Replacement",
    degrees: "MBBS, MS (Orthopedics)",
    hospital: "NH Mysore",
    hospitalCount: "",
    city: "Mysore",
    experience: "17 Years",
    rating: 4.6,
    reviews: 580,
    available: "Available Tomorrow",
    availability: {
      hospital: "Tomorrow, 04:00 PM",
      video: "Tomorrow, 06:00 PM"
    },
    img: "/images/misc/doctor_avatar_female_v2.png",
    fee: "₹1,100",
  },
  {
    id: "dr-21",
    name: "Dr. Vivek Anand",
    speciality: "Interventional Cardiology",
    degrees: "MBBS, MD, DM (Cardiology)",
    hospital: "NH Hosur",
    hospitalCount: "",
    city: "Hosur",
    experience: "13 Years",
    rating: 4.7,
    reviews: 490,
    available: "Available Today",
    availability: {
      hospital: "Today, 10:00 AM",
      video: "Today, 02:00 PM"
    },
    img: "/images/misc/doctor_avatar_male_v2.png",
    fee: "₹1,000",
  }
];
